services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        depends_on:
            - app
        volumes:
            #- ./docker/nginx-proxy/:/etc/nginx/conf.d/
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        networks:
            - fruit

    app:
        build:
            context: .
            dockerfile: ./docker/app/dev.Dockerfile
        volumes:
            - ./:/var/www/html
        environment:
            VIRTUAL_HOST: localhost
        depends_on:
            - db
        networks:
            - fruit

    db:
        image: mysql:8.0
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: fruit_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
            #- ./config.cnf:/etc/mysql/conf.d/config.cnf
        networks:
            - fruit

volumes:
    mysql_data:

networks:
    fruit:
        external: true
